import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/Header/NavBar";
import { AuthProvider } from "@/context/AuthContext";
import { ModalWrapper } from "@/context/ModalContext";
import { Geist, Geist_Mono } from "next/font/google";
import { ProfileProvider } from "@/context/ProfileContext";
import { ThemeProvider } from "@/context/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#EFEFEF]`}>
        <AuthProvider>
          <ProfileProvider>
            <ThemeProvider>
              <NavBar/>
              <ModalWrapper>{children}</ModalWrapper>
            </ThemeProvider>
          </ProfileProvider>
        </AuthProvider>
      </body>
    </html>
  );
}