import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/Header/NavBar";
import { AuthProvider } from "@/context/AuthContext";
import { ModalWrapper } from "@/context/ModalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#EFEFEF]`}>
        <AuthProvider>
          <NavBar />
          <ModalWrapper>{children}</ModalWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}