const profileHeaderStyles = {
  light: {
    container: "overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm",
    cover: "relative h-48 w-full",
    coverImage: "object-cover",
    content: "relative p-6",
    avatarWrapper: "absolute -top-12 right-6",
    avatarContainer: "relative h-24 w-24 overflow-hidden rounded-full border-4 border-white shadow-md",
    avatarImage: "object-cover",
    infoContainer: "mt-12 text-right",
    headerRow: "flex flex-row-reverse items-center justify-end gap-2",
    name: "text-2xl font-bold text-gray-900",
    bio: "mt-2 text-gray-600 text-right",
    contactContainer: "mt-4 flex flex-col justify-end gap-4 text-sm text-gray-500",
    contactRow: "flex items-center gap-1 justify-start",
    socialContainer: "mt-4 flex flex-row-reverse items-center justify-start gap-4 text-xl text-gray-400",
    socialLinkX: "hover:text-blue-400",
    socialLinkFacebook: "hover:text-blue-600",
    socialLinkLinkedin: "hover:text-blue-500",
    editButton: "text-gray-500 hover:text-gray-700",
  },
  dark: {
    container: "overflow-hidden rounded-xl border border-gray-700 bg-gray-900 shadow-sm",
    cover: "relative h-48 w-full",
    coverImage: "object-cover",
    content: "relative p-6",
    avatarWrapper: "absolute -top-12 right-6",
    avatarContainer: "relative h-24 w-24 overflow-hidden rounded-full border-4 border-gray-800 shadow-md",
    avatarImage: "object-cover",
    infoContainer: "mt-12 text-right",
    headerRow: "flex flex-row-reverse items-center justify-end gap-2",
    name: "text-2xl font-bold text-gray-100",
    bio: "mt-2 text-gray-300 text-right",
    contactContainer: "mt-4 flex flex-col justify-end gap-4 text-sm text-gray-400",
    contactRow: "flex items-center gap-1 justify-start",
    socialContainer: "mt-4 flex flex-row-reverse items-center justify-start gap-4 text-xl text-gray-400",
    socialLinkX: "hover:text-blue-400",
    socialLinkFacebook: "hover:text-blue-400",
    socialLinkLinkedin: "hover:text-blue-300",
    editButton: "text-gray-400 hover:text-gray-200",
  },
};

export default profileHeaderStyles;
