const profilePageSkeletonStyles = {
    container: "flex flex-col gap-6 animate-pulse",
    topBar: "h-8 w-1/3 bg-gray-200 rounded",
    mainRow: "flex flex-col lg:flex-row gap-6",
    mainContent: "flex-1 flex flex-col gap-6",
    profileHeader: "border border-gray-200 bg-white rounded-md p-4 space-y-4",
    coverImage: "h-32 bg-gray-200 rounded",
    profileRow: "flex items-center gap-4 -mt-8 px-4",
    avatar: "w-16 h-16 rounded-full bg-gray-200 border-4 border-white",
    profileInfo: "flex-1 space-y-2",
    infoLine1: "h-4 w-1/3 bg-gray-200 rounded",
    infoLine2: "h-3 w-1/2 bg-gray-200 rounded",
    bioSection: "space-y-2",
    bioTitle: "h-4 w-1/4 bg-gray-200 rounded",
    bioContent: "border border-gray-200 bg-white rounded-md p-4 space-y-3",
    bioLine1: "h-3 w-full bg-gray-200 rounded",
    bioLine2: "h-3 w-5/6 bg-gray-200 rounded",
    bioLine3: "h-3 w-2/3 bg-gray-200 rounded",
    articlesSection: "space-y-2",
    articlesTitle: "h-4 w-1/4 bg-gray-200 rounded",
    articleCard: "border border-gray-200 bg-white rounded-md p-4 flex flex-col md:flex-row gap-4",
    articleContent: "flex-1 space-y-2",
    articleLine1: "h-3 w-3/4 bg-gray-200 rounded",
    articleLine2: "h-3 w-1/2 bg-gray-200 rounded",
    articleLine3: "h-3 w-2/3 bg-gray-200 rounded",
    articleImage: "w-full md:w-40 h-24 bg-gray-200 rounded",
  };
  
  export default profilePageSkeletonStyles;
  